#!/bin/bash

export PACKAGE_CORE_NAME="maven-mvnd"
export PACKAGE_CORE_BIN_NAME="mvnd"
export PACKAGE_CORE_VERSION=v1.0.0-m1
export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/apache/maven-mvnd/releases/download"
